//* 
var urlParams = new URLSearchParams(window.location.search);
//*

const serverInfo = {
    "JBTS": {
        "name": "Jailbreak Trading Shifters",
        "shortHand": "JBTS",
        "memberCount": "1276",
        "date": "11/07/22",
        "focus": "Trading",
        "serverImage": "images/F9DFE05A-5DD1-43C4-B268-F0F57114884E_1_201_a.jpeg",
        "serverLink": "discord.gg/jbts",
        "serverGif": "images/IMG_8198.GIF",
        "channelCount": "27",
        "giveawayFrequency": "Often",
        "boosterPerks": "3x Entries",
        "giveawayTop3": "HyperShift, 10x Torpedos, 2x Torpedos",
    },
    "JBV": {
        "name": "JB Values (JBV)",
        "shortHand": "JBV",
        "memberCount": "47168",
        "date": "9/28/22",
        "focus": "Values",
        "serverImage": "images/IMG_7798.jpeg",
        "serverLink": "discord.gg/jbv",
        "serverGif": "images/jbvalues_banner.gif",
        "channelCount": "110",
        "giveawayFrequency": "Very Often",
        "boosterPerks": "2x Entries",
        "giveawayTop3": "20x Season Passes, 8x Beignets, Red 5",
    },
    "JBNation": {
        "name": "Jailbreak Nation",
        "shortHand": "JBN",
        "memberCount": "2132",
        "date": "05/27/23",
        "focus": "Giveaways",
        "serverImage": "images/B7B1F86D-8AA9-490C-B97A-CED3AB62AE29_1_201_a.jpeg",
        "serverLink": "discord.gg/jbn",
        "serverGif": "images/IMG_8198.GIF",
        "channelCount": "22",
        "giveawayFrequency": "Often",
        "boosterPerks": "2x Claim Time",
        "giveawayTop3": "Hypershift, 7x Celsiors, 2x Torpedos",
    },
    "JBSellers": {
        "name": "",
        "shortHand": "",
        "memberCount": "",
        "date": "",
        "focus": "",
        "serverImage": "",
        "serverLink": "",
        "serverGif": "images/IMG_8198.GIF",
        "channelCount": "",
        "giveawayFrequency": "",
        "boosterPerks": "",
        "giveawayTop3": "",
    },
    "JBBananas": {
        "name": "",
        "shortHand": "",
        "memberCount": "",
        "date": "",
        "focus": "",
        "serverImage": "",
        "serverLink": "",
        "serverGif": "images/IMG_8198.GIF",
        "channelCount": "",
        "giveawayFrequency": "",
        "boosterPerks": "",
        "giveawayTop3": "",
    },
    "JBTC": {
        "name": "",
        "shortHand": "",
        "memberCount": "",
        "date": "",
        "focus": "",
        "serverImage": "",
        "serverLink": "",
        "serverGif": "images/IMG_8198.GIF",
        "channelCount": "",
        "giveawayFrequency": "",
        "boosterPerks": "",
        "giveawayTop3": "",
    },
    "JBGrinders": {
        "name": "",
        "shortHand": "",
        "memberCount": "",
        "date": "",
        "focus": "",
        "serverImage": "",
        "serverLink": "",
        "serverGif": "images/IMG_8198.GIF",
        "channelCount": "",
        "giveawayFrequency": "",
        "boosterPerks": "",
        "giveawayTop3": "",
    },
    "JBCash": {
        "name": "Jailbreak Cash",
        "shortHand": "JB Cash",
        "memberCount": "2102",
        "date": "06/12/23",
        "focus": "Grinding",
        "serverImage": "images/jbcash.gif",
        "serverLink": "https://discord.gg/jailbreak-cash-1117903758614069359",
        "serverGif": "images/IMG_8198.GIF",
        "channelCount": "17",
        "giveawayFrequency": "Moderate",
        "boosterPerks": "x2 Entries",
        "giveawayTop3": "Torpedo, x2 Icebreakers, x2 Beam Hybrids",
    },
    "NPCTrade": {
        "name": "",
        "shortHand": "",
        "memberCount": "",
        "date": "",
        "focus": "",
        "serverImage": "",
        "serverLink": "",
        "serverGif": "images/IMG_8198.GIF",
        "channelCount": "",
        "giveawayFrequency": "",
        "boosterPerks": "",
        "giveawayTop3": "",
    },
    "JBStreet": {
        "name": "",
        "shortHand": "",
        "memberCount": "",
        "date": "",
        "focus": "",
        "serverImage": "",
        "serverLink": "",
        "serverGif": "images/IMG_8198.GIF",
        "channelCount": "",
        "giveawayFrequency": "",
        "boosterPerks": "",
        "giveawayTop3": "",
    },
    "JBEnforcers": {
        "name": "",
        "shortHand": "",
        "memberCount": "",
        "date": "",
        "focus": "",
        "serverImage": "",
        "serverLink": "",
        "serverGif": "images/IMG_8198.GIF",
        "channelCount": "",
        "giveawayFrequency": "",
        "boosterPerks": "",
        "giveawayTop3": "",
    },
    "JBBeach": {
        "name": "",
        "shortHand": "",
        "memberCount": "",
        "date": "",
        "focus": "",
        "serverImage": "",
        "serverLink": "",
        "serverGif": "images/IMG_8198.GIF",
        "channelCount": "",
        "giveawayFrequency": "",
        "boosterPerks": "",
        "giveawayTop3": "",
    },
    "": {
        "name": "",
        "shortHand": "",
        "memberCount": "",
        "date": "",
        "focus": "",
        "serverImage": "",
        "serverLink": "",
        "serverGif": "",
        "channelCount": "",
        "giveawayFrequency": "",
        "boosterPerks": "",
        "giveawayTop3": "",
    },
}

function updateServerInfo(serverName) {
    const info = serverInfo[serverName];
    document.getElementById("nameboxtoptext").innerHTML = info.name; 
    document.getElementById("ServerGif").src = info.serverGif;
    document.getElementById("InfoTop").innerHTML = info.shortHand + " - Info"; 
    document.getElementById("Members").innerHTML = "Members - " + info.memberCount;
    document.getElementById("CreDate").innerHTML = "Created - " + info.date;
    document.getElementById("Focus").innerHTML = "Focus - " + info.focus;
    document.getElementById("ServerImg").src = info.serverImage;
    document.getElementById("ServerLink").href = info.serverLink;
    document.getElementById("Channels").innerHTML = "Channels - " + info.channelCount;
    document.getElementById("Freq").innerHTML = "Giveaway Frequency - " + info.giveawayFrequency;
    document.getElementById("Boost").innerHTML = "Booster Perks - " + info.boosterPerks;
    document.getElementById("Top3").innerHTML = info.giveawayTop3;
}  

if (urlParams.has("JBTS")) {updateServerInfo("JBTS");}
if (urlParams.has("JBV")) {updateServerInfo("JBV");}
if (urlParams.has("JBCash")) {updateServerInfo("JBCash");}
